version: '3'
networks:
  my_network:
    driver: bridge
services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always # | unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_MAX_CONNECTIONS: 5000  # increase connection limit to 500.
      POSTGRES_DB: streamdb

  listener-service:
    build:
      context: ./listener-service
      dockerfile: Dockerfile
    container_name: listener-service
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - my_network

  emitter-service:
    build:
      context: ./emitter-service
      dockerfile: Dockerfile
    container_name: emitter-service
    restart: unless-stopped
    depends_on:
      - listener-service
    networks:
      - my_network


volumes:
  postgres_data: